// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb5wU8dFCocGi9f0bsdlkB5k31M3BEVI4',
    appId: '1:318428550858:web:9354f31101c1c4b9c18633',
    messagingSenderId: '318428550858',
    projectId: 'nambur-connect-app',
    authDomain: 'nambur-connect-app.firebaseapp.com',
    storageBucket: 'nambur-connect-app.firebasestorage.app',
    measurementId: 'G-Z8VDZ4ZJ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPtGEEERglHE6qMPQZWatU3PJZ1obQ3g',
    appId: '1:318428550858:android:b14ec3ee45d71cc2c18633',
    messagingSenderId: '318428550858',
    projectId: 'nambur-connect-app',
    storageBucket: 'nambur-connect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqkPTgKEvkQgj2PQOFJcnkXsOaHybzocs',
    appId: '1:318428550858:ios:a661108cd78b1e65c18633',
    messagingSenderId: '318428550858',
    projectId: 'nambur-connect-app',
    storageBucket: 'nambur-connect-app.firebasestorage.app',
    iosBundleId: 'com.example.namburConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqkPTgKEvkQgj2PQOFJcnkXsOaHybzocs',
    appId: '1:318428550858:ios:a661108cd78b1e65c18633',
    messagingSenderId: '318428550858',
    projectId: 'nambur-connect-app',
    storageBucket: 'nambur-connect-app.firebasestorage.app',
    iosBundleId: 'com.example.namburConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb5wU8dFCocGi9f0bsdlkB5k31M3BEVI4',
    appId: '1:318428550858:web:93712eced199dee3c18633',
    messagingSenderId: '318428550858',
    projectId: 'nambur-connect-app',
    authDomain: 'nambur-connect-app.firebaseapp.com',
    storageBucket: 'nambur-connect-app.firebasestorage.app',
    measurementId: 'G-JWLDD5CKE1',
  );
}
